export const initialData = [
    {
        id: 1,
        username: "Lionel Messi",
        age: 27,
        leagues: ["Laliga", "League1", "League2", "League3"],
        status: "active",
        height: 1.7,
        position: "forward",
    },
    {
        id: 2,
        username: "Cristiano Ronaldo",
        age: 36,
        leagues: ["Premier League", "Serie A", "LaLiga", "Saudi Pro League"],
        status: "active",
        height: 1.87,
        position: "forward",
    },
    {
        id: 3,
        username: "Neymar Jr",
        age: 29,
        leagues: ["Ligue 1", "LaLiga", "Brasileirao"],
        status: "active",
        height: 1.75,
        position: "forward",
    },
    {
        id: 4,
        username: "Kylian Mbappe",
        age: 22,
        leagues: ["Ligue 1", "Champions League"],
        status: "active",
        height: 1.78,
        position: "forward",
    },
    {
        id: 5,
        username: "Virgil Van Dijk",
        age: 30,
        leagues: ["Premier League", "Eredivisie"],
        status: "active",
        height: 1.93,
        position: "defender",
    },
    {
        id: 6,
        username: "Kevin De Bruyne",
        age: 29,
        leagues: ["Premier League", "Bundesliga"],
        status: "active",
        height: 1.81,
        position: "midfielder",
    },
    {
        id: 7,
        username: "Robert Lewandowski",
        age: 32,
        leagues: ["Bundesliga", "LaLiga"],
        status: "active",
        height: 1.85,
        position: "forward",
    },
    {
        id: 8,
        username: "Manuel Neuer",
        age: 35,
        leagues: ["Bundesliga"],
        status: "active",
        height: 1.93,
        position: "goalkeeper",
    },
    {
        id: 9,
        username: "Paul Pogba",
        age: 28,
        leagues: ["Premier League", "Serie A"],
        status: "active",
        height: 1.91,
        position: "midfielder",
    },
    {
        id: 10,
        username: "Erling Haaland",
        age: 21,
        leagues: ["Bundesliga", "Premier League"],
        status: "active",
        height: 1.94,
        position: "forward",
    },
    {
        id: 11,
        username: "Mo Salah",
        age: 29,
        leagues: ["Premier League", "Serie A", "Swiss League"],
        status: "active",
        height: 1.75,
        position: "forward",
    },
    {
        id: 12,
        username: "Luka Modric",
        age: 36,
        leagues: ["LaLiga", "Premier League"],
        status: "active",
        height: 1.72,
        position: "midfielder",
    },
    {
        id: 13,
        username: "Sergio Ramos",
        age: 35,
        leagues: ["LaLiga", "Ligue 1"],
        status: "active",
        height: 1.84,
        position: "defender",
    },
    {
        id: 14,
        username: "Zlatan Ibrahimovic",
        age: 40,
        leagues: ["Serie A", "LaLiga", "MLS"],
        status: "active",
        height: 1.95,
        position: "forward",
    },
    {
        id: 15,
        username: "Eden Hazard",
        age: 30,
        leagues: ["Premier League", "LaLiga"],
        status: "active",
        height: 1.75,
        position: "forward",
    },
    {
        id: 16,
        username: "Thibaut Courtois",
        age: 29,
        leagues: ["LaLiga", "Premier League"],
        status: "active",
        height: 1.99,
        position: "goalkeeper",
    },
    {
        id: 17,
        username: "Harry Kane",
        age: 28,
        leagues: ["Premier League"],
        status: "active",
        height: 1.88,
        position: "forward",
    },
    {
        id: 18,
        username: "Raheem Sterling",
        age: 27,
        leagues: ["Premier League"],
        status: "active",
        height: 1.7,
        position: "forward",
    },
    {
        id: 19,
        username: "Sadio Mane",
        age: 29,
        leagues: ["Premier League", "Bundesliga"],
        status: "active",
        height: 1.74,
        position: "forward",
    },
    {
        id: 20,
        username: "Gerard Pique",
        age: 34,
        leagues: ["LaLiga", "Premier League"],
        status: "retired",
        height: 1.94,
        position: "defender",
    },
];
